-- Insert Top 50 Native Coins into token_whitelist
-- Data includes symbol, name, coingecko_id, and logo_url

INSERT INTO public.token_whitelist (symbol, name, coingecko_id, logo_url) VALUES
('BTC', 'Bitcoin', 'bitcoin', 'https://assets.coingecko.com/coins/images/1/large/bitcoin.png'),
('ETH', 'Ethereum', 'ethereum', 'https://assets.coingecko.com/coins/images/279/large/ethereum.png'),
('BNB', 'BNB', 'binancecoin', 'https://assets.coingecko.com/coins/images/825/large/bnb-icon2_2x.png'),
('SOL', 'Solana', 'solana', 'https://assets.coingecko.com/coins/images/4128/large/solana.png'),
('XRP', 'XRP', 'ripple', 'https://assets.coingecko.com/coins/images/44/large/xrp-symbol-white-128.png'),
('ADA', 'Cardano', 'cardano', 'https://assets.coingecko.com/coins/images/975/large/cardano.png'),
('AVAX', 'Avalanche', 'avalanche-2', 'https://assets.coingecko.com/coins/images/12559/large/Avalanche_Circle_RedWhite_Trans.png'),
('DOGE', 'Dogecoin', 'dogecoin', 'https://assets.coingecko.com/coins/images/5/large/dogecoin.png'),
('TRX', 'TRON', 'tron', 'https://assets.coingecko.com/coins/images/1094/large/tron-logo.png'),
('DOT', 'Polkadot', 'polkadot', 'https://assets.coingecko.com/coins/images/12171/large/polkadot.png'),
('MATIC', 'Polygon', 'matic-network', 'https://assets.coingecko.com/coins/images/4713/large/matic-token-icon.png'),
('LTC', 'Litecoin', 'litecoin', 'https://assets.coingecko.com/coins/images/2/large/litecoin.png'),
('SHIB', 'Shiba Inu', 'shiba-inu', 'https://assets.coingecko.com/coins/images/11939/large/shiba.png'),
('BCH', 'Bitcoin Cash', 'bitcoin-cash', 'https://assets.coingecko.com/coins/images/780/large/bitcoin-cash-circle.png'),
('UNI', 'Uniswap', 'uniswap', 'https://assets.coingecko.com/coins/images/12504/large/uni.jpg'),
('LINK', 'Chainlink', 'chainlink', 'https://assets.coingecko.com/coins/images/877/large/chainlink-new-logo.png'),
('ATOM', 'Cosmos', 'cosmos', 'https://assets.coingecko.com/coins/images/1481/large/cosmos_hub.png'),
('XLM', 'Stellar', 'stellar', 'https://assets.coingecko.com/coins/images/100/large/Stellar_symbol_black_RGB.png'),
('XMR', 'Monero', 'monero', 'https://assets.coingecko.com/coins/images/69/large/monero_logo.png'),
('ETC', 'Ethereum Classic', 'ethereum-classic', 'https://assets.coingecko.com/coins/images/453/large/ethereum-classic-logo.png'),
('NEAR', 'NEAR Protocol', 'near', 'https://assets.coingecko.com/coins/images/10365/large/near.jpg'),
('ALGO', 'Algorand', 'algorand', 'https://assets.coingecko.com/coins/images/4380/large/download.png'),
('FIL', 'Filecoin', 'filecoin', 'https://assets.coingecko.com/coins/images/12817/large/filecoin.png'),
('VET', 'VeChain', 'vechain', 'https://assets.coingecko.com/coins/images/1167/large/VeChain-Logo-768x725.png'),
('APT', 'Aptos', 'aptos', 'https://assets.coingecko.com/coins/images/26455/large/aptos_round.png'),
('HBAR', 'Hedera', 'hedera-hashgraph', 'https://assets.coingecko.com/coins/images/3688/large/hbar.png'),
('ICP', 'Internet Computer', 'internet-computer', 'https://assets.coingecko.com/coins/images/14495/large/Internet_Computer_logo.png'),
('ARB', 'Arbitrum', 'arbitrum', 'https://assets.coingecko.com/coins/images/16547/large/photo_2023-03-29_21.47.00.jpeg'),
('OP', 'Optimism', 'optimism', 'https://assets.coingecko.com/coins/images/25244/large/Optimism.png'),
('INJ', 'Injective', 'injective-protocol', 'https://assets.coingecko.com/coins/images/12882/large/Secondary_Symbol.png'),
('SUI', 'Sui', 'sui', 'https://assets.coingecko.com/coins/images/26375/large/sui_asset.jpeg'),
('TIA', 'Celestia', 'celestia', 'https://assets.coingecko.com/coins/images/31967/large/tia.jpg'),
('SEI', 'Sei', 'sei-network', 'https://assets.coingecko.com/coins/images/28205/large/Sei_Logo_-_Transparent.png'),
('FTM', 'Fantom', 'fantom', 'https://assets.coingecko.com/coins/images/4001/large/Fantom_round.png'),
('AAVE', 'Aave', 'aave', 'https://assets.coingecko.com/coins/images/12645/large/aave-token-round.png'),
('EOS', 'EOS', 'eos', 'https://assets.coingecko.com/coins/images/738/large/eos-eos-logo.png'),
('XTZ', 'Tezos', 'tezos', 'https://assets.coingecko.com/coins/images/976/large/Tezos-logo.png'),
('THETA', 'Theta Network', 'theta-token', 'https://assets.coingecko.com/coins/images/2538/large/theta-token-logo.png'),
('FLOW', 'Flow', 'flow', 'https://assets.coingecko.com/coins/images/13446/large/5f6294c0c7a8cda55cb1c936_Flow_Wordmark.png'),
('EGLD', 'MultiversX', 'elrond-erd-2', 'https://assets.coingecko.com/coins/images/12335/large/egld-token-logo.png'),
('SAND', 'The Sandbox', 'the-sandbox', 'https://assets.coingecko.com/coins/images/12129/large/sandbox_logo.jpg'),
('MANA', 'Decentraland', 'decentraland', 'https://assets.coingecko.com/coins/images/878/large/decentraland-mana.png'),
('AXS', 'Axie Infinity', 'axie-infinity', 'https://assets.coingecko.com/coins/images/13029/large/axie_infinity_logo.png'),
('ZEC', 'Zcash', 'zcash', 'https://assets.coingecko.com/coins/images/486/large/circle-zcash-color.png'),
('KAVA', 'Kava', 'kava', 'https://assets.coingecko.com/coins/images/9761/large/kava.png'),
('NEO', 'Neo', 'neo', 'https://assets.coingecko.com/coins/images/480/large/NEO_512_512.png'),
('IOTA', 'IOTA', 'iota', 'https://assets.coingecko.com/coins/images/692/large/IOTA_Swirl.png'),
('DASH', 'Dash', 'dash', 'https://assets.coingecko.com/coins/images/19/large/dash-logo.png'),
('WAVES', 'Waves', 'waves', 'https://assets.coingecko.com/coins/images/425/large/waves.png'),
('ZIL', 'Zilliqa', 'zilliqa', 'https://assets.coingecko.com/coins/images/2687/large/Zilliqa-logo.png')
ON CONFLICT (symbol) DO NOTHING;